services:
  - type: web
    name: skribbl-clone
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
